### PR TITLE
brightness_contrast_adjust optimization

### PR DESCRIPTION
**Pull request by Dipet**
Before
```
                   albumentations imgaug torchvision keras augmentor  solt
Brightness                    128    529          77    25        80  1055
Contrast                      183    592          58     -        61   930
BrightnessContrast            140    340          34     -        33   527
```

After
```
                   albumentations imgaug torchvision keras augmentor  solt
Brightness                    987    594          80    24        81   984
Contrast                     1227    608          59     -        61  1191
BrightnessContrast           1266    356          35     -        35   373
```

### CODE REVIEW

**Comment by ternaus** [comment]
This speedup looks tempting. But we get it because of the change in the algorithm.

Could you please share what was the motivation behind it? Is it the way it is implemented in other libraries?

**Comment by Dipet** [comment]
1. I remove clipping from uint8 version (~2 times faster )
2.  Remove mean calculation from image and use dtype maximum.
imgaug [Add](https://github.com/aleju/imgaug/blob/38f305aaa5df833228d95d95de36e77d1a4ac88c/imgaug/augmenters/arithmetic.py#L51) and solt [ImageRandomBrightness](https://github.com/MIPT-Oulu/solt/blob/a6891d4dfa6bfd0d01a4ca1d6e7c03d15468d9c3/solt/transforms/_transforms.py#L1030) transforms use values for add from your interval but it will be in range [-dtype.max, dtype.max].
For example, we set interval [-25, 25] in this implementation it will be equivalent to [-25/256, 25/256]

**Comment by ternaus** [comment]
Benchmark and default behavior are different now. 

Let's delete the changes in the benchmark file. In version 0.4, they will start working automatically.

**Comment by Dipet** [comment]
@ternaus Benchmark changes removed

**Pull request merged**
