### PR TITLE
Update benchmark for 0.4.0

### PR DESCRIPTION
**Pull request by creafz**

### CODE REVIEW

**Comment by Dipet** [comment]
Need update Brightness - `albumentations.brightness_contrast_adjust(img, beta=0.5, beta_by_max=True)` - it is new behavior

**Comment by ternaus** [comment]
`birghtness_by_max=True` is the default behavior. I believe it is picked automatically.

**Comment by Dipet** [comment]
benchmark uses functional api, so need set this flag

**Comment by ternaus** [comment]
Also, I do not see transforms:

```
        Posterize(),
        Solarize(),
        Equalize(),
```

**Pull request merged**
